# .github/workflows/find_new_announcements.yml

name: Find new announcements with Robot Framework

on:
  # Runs the workflow on every push to main branch
  push:
    branches:
      - main
  # Allows manual triggering of the workflow
  workflow_dispatch:
  # Schedule to run every working day at 07 AM UTC (09 AM Finnish time) 
  schedule:
    - cron: '0 7 * * 1-5'

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # Set cache key for the last working day's data
    - name: Set cache key
      id: cache-key
      run: |
        if [ "$(date +%u)" -eq 1 ]; then # Monday
          # Use Friday's cache
          last_working_day=$(date +'%Y-%m-%d' -d 'last Friday')
        else
          # Use the previous day's cache
          last_working_day=$(date +'%Y-%m-%d' -d 'yesterday')
        fi
        echo "restore_key=cache-announcements-${last_working_day}" >> $GITHUB_ENV
        echo "key=cache-announcements-$(date +'%Y-%m-%d')" >> $GITHUB_ENV

    - name: Restore cached Announcements
      id: cache-data
      uses: actions/cache/restore@v4
      with:
        path: tests/testdata/assignments.json
        key: ${{ env.restore_key }}

    - name: Check if cache was restored
      run: |
        if [ ${{ steps.cache-data.outputs.cache-hit }} == 'true' ]; then
          echo "Cache was restored from previous run!"
        else
          echo "No cache found, running full setup."
        fi

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Create and activate virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt
        rfbrowser init
        
    - name: Run Robot Framework tests
      env:
          PYTHONPATH: ${{ github.workspace }}/src
          SLACK_URL: ${{ secrets.SLACK_URL }}
      run: | 
          source venv/bin/activate
          robot --outputdir results tests/announcement_bot.robot
    
    - name: Save Announcements
      uses: actions/cache/save@v4
      with:
        path: tests/testdata/assignments.json
        key: ${{ env.key }}
  

    - name: Archive Robot Framework results
      uses: actions/upload-artifact@v4
      with:
          name: robot-results
          path: results/
