# .github/workflows/robot-tests.yml

name: Run Robot Framework Tests

on:
  # Runs the workflow on every push to main branch
  push:
    branches:
      - main
  # Allows manual triggering of the workflow
  workflow_dispatch:
  # Schedule to run every day at 9 AM UTC
  schedule:
    - cron: '1 1 * * *'

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository code
    - name: Checkout repository
      uses: actions/checkout@v4

    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # Replace '3.x' with the desired Python version

    # Create and activate virtual environment
    - name: Install dependencies in venv
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt
        rfbrowser init

    # Download the JSON artifact from the previous run
    - name: Download JSON artifact
      uses: actions/download-artifact@v4
      with:
        name: assignments
        path: testdata/assignments.json
      continue-on-error: true

    - name: Check if JSON file exists and create if not
      run: |
        FILE_PATH="testdata/assignments.json"  # Define the file path here
        FOLDER_PATH=$(dirname "$FILE_PATH")
        
        # Check if the file exists
        if [ ! -f "$FILE_PATH" ]; then
          echo "File not found, creating folder and empty JSON file."
          mkdir -p "$FOLDER_PATH"  # Create folder if it doesnt exist
        else
          echo "File found: $FILE_PATH"
        fi
        

    # Run Robot Framework tests
    - name: Run Robot Framework tests
      env:
          PYTHONPATH: ${{ github.workspace }}/src  # Add 'src' to the PYTHONPATH
          SLACK_URL: ${{ secrets.SLACK_URL }}
      run: | 
          source venv/bin/activate
          robot --outputdir results -v ANNOUNCEMENTS_JSON:testdata/assignments.json tests/announcement_bot.robot
    
    # Upload JSON artifact
    - name: Upload JSON artifact
      uses: actions/upload-artifact@v4
      with:
        name: assignments
        path: testdata/assignments.json
        overwrite: true
        compression-level: 0

    # Upload test results
    - name: Archive Robot Framework results
      uses: actions/upload-artifact@v4
      with:
          name: robot-results
          path: results/
