# .github/workflows/robot-tests.yml

name: Run Robot Framework Tests

on:
  # Runs the workflow on every push to main branch
  push:
    branches:
      - main
  # Allows manual triggering of the workflow
  workflow_dispatch:
  # Schedule to run every day at 9 AM UTC
  schedule:
    - cron: '0 9 * * *'

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository code
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Git user for commit
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # Replace '3.x' with the desired Python version

    # Step 3: Create and activate virtual environment
    - name: Install dependencies in venv
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt
        rfbrowser init

    # Step 4: Run Robot Framework tests
    - name: Run Robot Framework tests
      env:
          PYTHONPATH: ${{ github.workspace }}/src  # Add 'src' to the PYTHONPATH
          SLACK_URL: ${{ secrets.SLACK_URL }}
      run: | 
          source venv/bin/activate
          robot --outputdir results tests/announcement_bot.robot
    
    # Step 5: Upload test results
    - name: Archive Robot Framework results
      uses: actions/upload-artifact@v4
      with:
          name: robot-results
          path: results/

    # Step 6: Commit and push JSON changes (for next run)
    - name: Commit and push JSON changes
      run: |
        git add tests/testdata/assignments.json
        git commit -m "Update JSON file with updates assignments"
        git push https://${{ secrets.GITHUB_TOKEN }}@github.com/qubilea-sadinmaki/assignment-crawler.git
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
