# .github/workflows/find_new_announcements.yml

name: Run Robot Framework Tests

on:
  # Runs the workflow on every push to main branch
  push:
    branches:
      - main
  # Allows manual triggering of the workflow
  workflow_dispatch:
  # Schedule to run every day at 07 AM UTC (09 AM Finnish time) 
  schedule:
    - cron: '0 7 * * 1-5'

jobs:
  fetch-artifacts:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Download artifact
        uses: actions/github-script@v6
        continue-on-error: true
        env:
          WORKFLOW_FILENAME: find_new_announcements.yml
          ARTIFACT_NAME: assignments
          ARTIFACT_FILENAME: assignments.zip
          UNZIP_DIR: tests/testdata
        with:
          script: |
            const script = require('./scripts/download-previous-artifact.js')
            await script({github, context, core}) 

  run-tests:
    runs-on: ubuntu-latest
    # We need to make sure that we have actions read access to get the previous artifact
    permissions:
      contents: read
      actions: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Create and activate virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt
        rfbrowser init
        
    - name: Run Robot Framework tests
      env:
          PYTHONPATH: ${{ github.workspace }}/src
          SLACK_URL: ${{ secrets.SLACK_URL }}
      run: | 
          source venv/bin/activate
          robot --outputdir results tests/announcement_bot.robot
    
    - name: Upload announcements JSON artifact
      uses: actions/upload-artifact@v4
      with:
        name: assignments
        path: tests/testdata/assignments.json
        overwrite: true
        compression-level: 0
        retention-days: 5

    - name: Archive Robot Framework results
      uses: actions/upload-artifact@v4
      with:
          name: robot-results
          path: results/
